import type { Permission } from './permissions.js';
import type { Role } from './roles.js';

// 'all'  = ✓ / ✓ (auditado) / ✓ (justificado) en la tabla de RFC-004: el rol
//          puede, en principio, ejercer el permiso sobre cualquier recurso
//          de su tenant. El matiz "auditado"/"justificado" (platform_support)
//          no es una celda distinta -- es la precondición de la escalada de
//          soporte de plataforma (ver servicio auth, endpoint
//          /v1/auth/support-access), no algo que este motor decida.
// 'own'   = ✓ (propio) / ✓ (pública, por posesión) / ✓ (self-service,
//          público): el rol puede ejercer el permiso, pero el filtro de QUÉ
//          recurso concreto es responsabilidad del repositorio del servicio
//          (regla ABAC, RFC-004 sección "Modelo elegido"), nunca de can().
// 'none'  = — : no aplica.
export type PermissionGrant = 'all' | 'own' | 'none';

export type PermissionMatrix = Record<Permission, Record<Role, PermissionGrant>>;

// Transcripción literal de la matriz rol×permiso de docs/rfc/RFC-004-rbac.md
// (sección "Matriz rol × permiso"). No reinterpretar: cualquier cambio a
// esta tabla es un cambio al RFC, no al código.
export const PERMISSION_MATRIX = {
  'auth:login': {
    platform_admin: 'all',
    platform_support: 'all',
    clinic_owner: 'all',
    clinic_admin: 'all',
    doctor: 'all',
    receptionist: 'all',
    patient: 'none',
  },
  'auth:refresh': {
    platform_admin: 'all',
    platform_support: 'all',
    clinic_owner: 'all',
    clinic_admin: 'all',
    doctor: 'all',
    receptionist: 'all',
    patient: 'none',
  },
  'user:create': {
    platform_admin: 'all',
    platform_support: 'none',
    clinic_owner: 'all',
    clinic_admin: 'none',
    doctor: 'none',
    receptionist: 'none',
    patient: 'none',
  },
  'user:list': {
    platform_admin: 'all',
    platform_support: 'all',
    clinic_owner: 'all',
    clinic_admin: 'all',
    doctor: 'none',
    receptionist: 'none',
    patient: 'none',
  },
  'user:deactivate': {
    platform_admin: 'all',
    platform_support: 'none',
    clinic_owner: 'all',
    clinic_admin: 'none',
    doctor: 'none',
    receptionist: 'none',
    patient: 'none',
  },
  'doctor:create': {
    platform_admin: 'all',
    platform_support: 'none',
    clinic_owner: 'all',
    clinic_admin: 'none',
    doctor: 'none',
    receptionist: 'none',
    patient: 'none',
  },
  'doctor:list': {
    platform_admin: 'all',
    platform_support: 'all',
    clinic_owner: 'all',
    clinic_admin: 'all',
    doctor: 'all',
    receptionist: 'all',
    patient: 'all',
  },
  'doctor:read': {
    platform_admin: 'all',
    platform_support: 'all',
    clinic_owner: 'all',
    clinic_admin: 'all',
    doctor: 'all',
    receptionist: 'all',
    patient: 'all',
  },
  'doctor:read_slots': {
    platform_admin: 'all',
    platform_support: 'all',
    clinic_owner: 'all',
    clinic_admin: 'all',
    doctor: 'all',
    receptionist: 'all',
    patient: 'all',
  },
  'doctor:manage_availability': {
    platform_admin: 'all',
    platform_support: 'none',
    clinic_owner: 'all',
    clinic_admin: 'all',
    doctor: 'own',
    receptionist: 'none',
    patient: 'none',
  },
  'patient:create': {
    platform_admin: 'all',
    platform_support: 'none',
    clinic_owner: 'none',
    clinic_admin: 'none',
    doctor: 'none',
    receptionist: 'all',
    patient: 'own',
  },
  'patient:read': {
    platform_admin: 'all',
    platform_support: 'all',
    clinic_owner: 'all',
    clinic_admin: 'all',
    doctor: 'own',
    receptionist: 'all',
    patient: 'own',
  },
  'patient:list': {
    platform_admin: 'all',
    platform_support: 'all',
    clinic_owner: 'all',
    clinic_admin: 'all',
    doctor: 'none',
    receptionist: 'all',
    patient: 'none',
  },
  'patient:update': {
    platform_admin: 'all',
    platform_support: 'none',
    clinic_owner: 'all',
    clinic_admin: 'all',
    doctor: 'none',
    receptionist: 'all',
    patient: 'none',
  },
  'appointment:create': {
    platform_admin: 'all',
    platform_support: 'none',
    clinic_owner: 'all',
    clinic_admin: 'all',
    doctor: 'none',
    receptionist: 'all',
    patient: 'own',
  },
  'appointment:read': {
    platform_admin: 'all',
    platform_support: 'all',
    clinic_owner: 'all',
    clinic_admin: 'all',
    doctor: 'own',
    receptionist: 'all',
    patient: 'own',
  },
  'appointment:list': {
    platform_admin: 'all',
    platform_support: 'all',
    clinic_owner: 'all',
    clinic_admin: 'all',
    doctor: 'own',
    receptionist: 'all',
    patient: 'none',
  },
  'appointment:cancel': {
    platform_admin: 'all',
    platform_support: 'none',
    clinic_owner: 'all',
    clinic_admin: 'all',
    doctor: 'own',
    receptionist: 'all',
    patient: 'own',
  },
  'appointment:complete': {
    platform_admin: 'all',
    platform_support: 'none',
    clinic_owner: 'all',
    clinic_admin: 'all',
    doctor: 'own',
    receptionist: 'all',
    patient: 'none',
  },
  'appointment:mark_no_show': {
    platform_admin: 'all',
    platform_support: 'none',
    clinic_owner: 'all',
    clinic_admin: 'all',
    doctor: 'own',
    receptionist: 'all',
    patient: 'none',
  },
  'dashboard:read': {
    platform_admin: 'all',
    platform_support: 'all',
    clinic_owner: 'all',
    clinic_admin: 'all',
    doctor: 'none',
    receptionist: 'none',
    patient: 'none',
  },
  'audit:read': {
    platform_admin: 'all',
    platform_support: 'all',
    clinic_owner: 'all',
    clinic_admin: 'none',
    doctor: 'none',
    receptionist: 'none',
    patient: 'none',
  },
  'dead_letter:read': {
    platform_admin: 'all',
    platform_support: 'all',
    clinic_owner: 'none',
    clinic_admin: 'none',
    doctor: 'none',
    receptionist: 'none',
    patient: 'none',
  },
  'dead_letter:retry': {
    platform_admin: 'all',
    platform_support: 'all',
    clinic_owner: 'none',
    clinic_admin: 'none',
    doctor: 'none',
    receptionist: 'none',
    patient: 'none',
  },
  'dead_letter:remove': {
    platform_admin: 'all',
    platform_support: 'all',
    clinic_owner: 'none',
    clinic_admin: 'none',
    doctor: 'none',
    receptionist: 'none',
    patient: 'none',
  },
  'payment:create_customer': {
    platform_admin: 'all',
    platform_support: 'none',
    clinic_owner: 'none',
    clinic_admin: 'none',
    doctor: 'none',
    receptionist: 'none',
    patient: 'none',
  },
  'payment:create_intent': {
    platform_admin: 'all',
    platform_support: 'none',
    clinic_owner: 'none',
    clinic_admin: 'none',
    doctor: 'none',
    receptionist: 'none',
    patient: 'none',
  },
  'payment:cancel_intent': {
    platform_admin: 'all',
    platform_support: 'none',
    clinic_owner: 'none',
    clinic_admin: 'none',
    doctor: 'none',
    receptionist: 'none',
    patient: 'none',
  },
  'payment:refund': {
    platform_admin: 'all',
    platform_support: 'none',
    clinic_owner: 'all',
    clinic_admin: 'none',
    doctor: 'none',
    receptionist: 'none',
    patient: 'none',
  },
} satisfies PermissionMatrix;
